MSG_SALDO_INSUFICIENTE = 'Saldo insuficiente!'
MSG_SUCESSO_SAQUE = 'Saque efetuado com sucesso!'
MSG_SUCESSO_TRANSFERENCIA= 'Transferência efetuada com sucesso!'
MSG_SUCESSO_DEPOSITO = 'Depósito efetuado com sucesso!'
MSG_ERRO_SAQUE = 'Ocorreu um erro ao efetuar o saque!'
MSG_ERRO_TRANSFERENCIA = 'Ocorreu um erro ao efetuar a transferência!'
MSG_ERRO_DEPOSITO = 'Ocorreu um erro ao efetuar o depósito!'